version: "3.8"
services:
  reverse-proxy:
    image: traefik:v2.8
    command:
      - "--providers.file.directory=/configuration/"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/configuration/traefik.yml
      - ${SSL_CERT_KEY:-./cert/certificate.key}:/cert/certificate.key
      - ${SSL_CERT_CRT:-./cert/certificate.crt}:/cert/certificate.crt

  # https://bluecity.epfl.ch
  bluecity:
    build: hosts/bluecity.epfl.ch/
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bluecity.tls=true"
      - "traefik.http.routers.bluecity.rule=PathPrefix(`/`)"
      - "traefik.http.routers.bluecity.rule=Host(`bluecity.epfl.ch`)"

  # https://enacit1.epfl.ch
  enacit1-redirect:
    build: hosts/enacit1.epfl.ch/
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enacit1-redirect.tls=true"
      - "traefik.http.routers.enacit1-redirect.rule=PathPrefix(`/`)"
      - "traefik.http.routers.enacit1-redirect.rule=Host(`enacit1.epfl.ch`)"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

  # https://enacit1.epfl.ch/ideas-mineur-form
  # https://enacit1.epfl.ch/charte2010
  enacit1-ideas-mineur-app:
    build: hosts/enacit1.epfl.ch/enacit1-ideas-mineur-form
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enacit1-ideas-mineur-app.tls=true"
      - "traefik.http.routers.enacit1-ideas-mineur-app.rule=(Host(`enacit1.epfl.ch`) && PathPrefix(`/ideas-mineur-form`))"
      - "traefik.http.routers.enacit1-ideas-mineur-app.service=enacit1-ideas-mineur-app-service"
      - "traefik.http.services.enacit1-ideas-mineur-app-service.loadbalancer.server.port=80"
      - "traefik.http.routers.enacit1-charte2010.tls=true"
      - "traefik.http.routers.enacit1-charte2010.rule=(Host(`enacit1.epfl.ch`) && PathPrefix(`/charte2010`))"
      - "traefik.http.routers.enacit1-charte2010.service=enacit1-charte2010-service"
      - "traefik.http.services.enacit1-charte2010-service.loadbalancer.server.port=80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - hosts/enacit1.epfl.ch/enacit1-ideas-mineur-form/.env

  # https://enacit1.epfl.ch/reserv-vehicules
  enacit1-reserv-vehicules:
    build: hosts/enacit1.epfl.ch/enacit1-reserv-vehicules
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enacit1-reserv-vehicules.tls=true"
      - "traefik.http.routers.enacit1-reserv-vehicules.rule=(Host(`enacit1.epfl.ch`) && PathPrefix(`/reserv-vehicules`))"
      - "traefik.http.routers.enacit1-reserv-vehicules.service=enacit1-reserv-vehicules-service"
      - "traefik.http.services.enacit1-reserv-vehicules-service.loadbalancer.server.port=80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - hosts/enacit1.epfl.ch/enacit1-reserv-vehicules/.env
      - hosts/enacit1.epfl.ch/enacit1-reserv-vehicules/.secret.env

  enacit1-reserv-vehicules-mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - enacit1-reserv-vehicules-mysql-data:/var/lib/mysql
    env_file:
      - hosts/enacit1.epfl.ch/enacit1-reserv-vehicules/.env
      - hosts/enacit1.epfl.ch/enacit1-reserv-vehicules/.secret.env

  enacit1-reserv-vehicules-cron:
    build: hosts/enacit1.epfl.ch/enacit1-reserv-vehicules/cron
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - hosts/enacit1.epfl.ch/enacit1-reserv-vehicules/.env
      - hosts/enacit1.epfl.ch/enacit1-reserv-vehicules/.secret.env


volumes:
  enacit1-reserv-vehicules-mysql-data:
    driver: local
