services:
  # https://bluecity.epfl.ch
  bluecity:
    build: hosts/bluecity.epfl.ch/
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bluecity.tls=true"
      - "traefik.http.routers.bluecity.rule=PathPrefix(`/`)"
      - "traefik.http.routers.bluecity.rule=Host(`bluecity.epfl.ch`)"
    volumes:
      - /etc/localtime:/etc/localtime:ro
