name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [bug, triage]
assignees: [sbancal, ylondero, alejos]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: What URL is problematic?
      placeholder: ex. https://something.epfl.ch/bla/foo/bar.html
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        if more complicated than just go to the URL, then tell us here the steps:
        1. When I'm here
        2. I click on ...
        3. See error...
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description: |
        what is your Operating system + browser
      placeholder: e.g. Windows + Firefox, Mac OS + Chromium
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
